### ISSUE TITLE
Comments not tracking

### ISSUE THREAD

**Issue by jeffutter** [thoughtbot/pester#130]
From the guide it seems that PRs with comments on them should be "In Progress". I'm assuming this means that they will not notify the channel (I haven't ran beggar long enough to confirm this).

It would be nice if the UI showed the PRs that are in progress as such. Currently it seems that they still show up as "Needs Review"

If I am understanding how this should work correctly I can work on submitting a fix.

**Comment by jeffutter** [comment]
Looking a little further, it looks like this should be supported. The problem I am seeing then is that when I add comments (Either myself, or a coworker) they are not being tracked by beggar. (it still shows the little icon comment followed by 0)

Is anyone else experiencing this?

**Comment by drapergeek** [comment]
I haven't tested this but the only way that PRs will move to in progress right now is by a comment on a line of code. Putting a comment at the bottom of a PR is an "issue_comment" to GH and we don't track those as part of the "In progress" status. Is that what you're seeing?

This is not "by design", just something that was overlooked so if it is something you'd like added, I'm happy to accept a PR for that.

**Comment by jeffutter** [comment]
Ahh, yes that is what I was seeing. I'll look into submitting a PR for this. Thanks.

**Comment by ivantedja** [comment]
it seems to have been abandoned for a long time, I'm interested to submit a PR for this
